#! /usr/bin/env node

module.exports = function GameOfLife(defaultBoard){
    defaultBoard = defaultBoard.trim();
    gameBoard = defaultBoard.split("\n").map(function(value){
        return value.split("");
    });
    const IsAlive = {"x":0,
                    "o":1,
                    "undefined":0};
    const AliveNext = {
                    "o":{"2":"o","3":"o"},
                     "x":{"3":"o"},
                     "undefined":{"3":"o"}
                  }
    const ConvertDead = {"x":"x",
                        "o":"o",
                        "undefined":"x"
                    }
    for (let row = 0; row < gameBoard.length; row ++){
        for (let column = 0; column < gameBoard.length; column ++){
            currentStatus = gameBoard[row][column];
            let neighbors = checkNeighbors(row, column, gameBoard);
            neighbors -= IsAlive[currentStatus];
            gameBoard[row][column] = AliveNext[currentStatus][neighbors];
        }
    }
    return gameBoard.map(function (value){
        return ConvertDead[value];
    });

}


var checkNeighbors = function(row, col, array) {
    var count = 0;
    var isAlive = {
        o: 1,
        undefined: 0,
    }
    for (var i = Math.max(0, row - 2); i < Math.min(array.length, row + 2); i++) {
        debugger;
        for (var j = Math.max(0, col - 2); j < Math.min(array[row].length, col + 2); j++) {
            debugger;
            count += isAlive[array[i][j]];
        }
    }
    return count;
}
